# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build_example:

    runs-on: self-hosted
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: act10ns/slack@v1
      with:
        status: starting
        channel: '#pruebas-git-hub'
      if: always()
    - uses: actions/checkout@v2

    - name: Variable de entorno
      run: echo ${{ env.MENSAJE }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present

    - uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#pruebas-git-hub'
      if: always()

  enviroment_example:

    runs-on: ubuntu-latest
    env:
      MENSAJE : Este mensaje es de una variable de entorno!!!!

    steps:
      - uses: actions/checkout@v2

      - name: Variable de entorno
        run: echo ${{ env.MENSAJE }}
